### ISSUE TITLE
Will Uninstall-Module revert to the previous functionality

### ISSUE THREAD

**Issue by Liturgist** [Jaykul/BetterCredentials#16]
I understand the use of -AllowClobber.

Will Uninstall-Module revert back to the previous functionality?

**Comment by Jaykul** [comment]
Yes. 

Additionally, in every case, PowerShell allows you to re-import modules, and the most recently imported module gets the default name -- the other module has to be called explicitly.

```PowerShell
Microsoft.PowerShell.Security\Get-Credential
```

Will work to call the built-in version, even with BetterCredential imported.
