### ISSUE TITLE
Test-Credential not exported

### ISSUE THREAD

**Issue by mattmcnabb** [Jaykul/BetterCredentials#4]
Looks like in the version of the module on the PSGallery, the Test-Credential function is not exported. In the GH repo it is, and both have the same module version number:
![untitled](https://cloud.githubusercontent.com/assets/6998507/23212861/9771ab3e-f8d6-11e6-8e44-ae2a09a4dfab.png)

**Comment by Jaykul** [comment]
Fixed, and added this one and all the aliases too. 
4.5 released.
