### ISSUE TITLE
Compatibility with Powershell Core

### ISSUE THREAD

**Issue by lipkau** [Jaykul/BetterCredentials#5]
@jaykul How will this work with PowerShell 6 on Linux and Mac?

**Comment by Jaykul** [comment]
At this time, it will not.
It uses the Windows-only "Credential Manager" vault.

I considered using the DataProtection API (which is approximately as secure, but has some flexibility to store things per-computer, instead per-user), but that wouldn't help you anyway.

The last time I checked, there weren't working data protection APIs in core -- I don't believe that's true anymore, so _something_ can be worked out in a cross-platform manner. I'll have a look.

**Comment by AdilHindistan** [comment]
I am guessing this never happened?

**Comment by Jaykul** [comment]
Yeah, it basically can't be done cross-platform.

The only data protection code in .NET Core requires you to manage a key, because without Windows, there's no automatic managed keys for DPAPI.

I have some other ideas, but they're going to require a totally different approach.
