### ISSUE TITLE
A path forward for cross-platform

### ISSUE THREAD

**Issue by Jaykul** [Jaykul/BetterCredentials#7]
In order to support PowerShell Core _on platforms other than Windows_, it's necessary to abstract the credential storage part of this module out into something where we can plug in different solutions on different platforms. For instance:

* **Windows** Credential Vault
* **MacOS** Keychain
* **Linux** D-Bus secret service, or `pass`

Something like [Docker's Credential Helpers](https://github.com/docker/docker-credential-helpers) seems to be the best approach, although we can't just use theirs, because their plugins and client library are written in Go, which doesn't really interop with ... anything.

**Comment by Jaykul** [comment]
Obviously Microsoft decided to tackle this. I'm just not going to bother trying to compete with that.

**Comment by Liturgist** [comment]
It has been over a year. What is the current Microsoft plan for this? Is it available?

**Comment by Jaykul** [comment]
It is available, and is on the gallery and here:
https://github.com/PowerShell/SecretManagement
